use super::AutoGeneratedGroupMetadata;
use alloc::borrow::Cow;
use core::cmp::Ordering;
use serde::{Deserialize, Serialize};

pub(crate) const AUTO_GENERATED_GROUP_MARKER: &str = "✨";

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    Hash,
    Serialize,
    Deserialize,
)]
pub(crate) struct GroupName(Cow<'static, str>);

impl GroupName {
    pub(crate) fn as_str(&self) -> &str {
        &self.0
    }
}

impl<'a> From<&'a GroupName> for Cow<'a, str> {
    fn from(val: &'a GroupName) -> Self {
        Cow::Borrowed(val.as_str())
    }
}

impl From<&'static str> for GroupName {
    fn from(s: &'static str) -> Self {
        Self(s.into())
    }
}

impl From<String> for GroupName {
    fn from(s: String) -> Self {
        Self(s.into())
    }
}

impl From<&AutoGeneratedGroupMetadata> for GroupName {
    fn from(metadata: &AutoGeneratedGroupMetadata) -> Self {
        format!(
            "{}::{}::{} {}",
            metadata.package_name,
            metadata.target_name,
            metadata.target_kind,
            AUTO_GENERATED_GROUP_MARKER
        )
        .into()
    }
}

#[allow(clippy::missing_trait_methods)]
impl PartialOrd for GroupName {
    fn partial_cmp(
        &self,
        other: &Self,
    ) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

#[allow(clippy::missing_trait_methods)]
impl Ord for GroupName {
    fn cmp(&self, other: &Self) -> Ordering {
        match (
            self.0.ends_with(AUTO_GENERATED_GROUP_MARKER),
            other.0.ends_with(AUTO_GENERATED_GROUP_MARKER),
        ) {
            (true, false) => Ordering::Greater,
            (false, true) => Ordering::Less,
            _ => self.0.cmp(&other.0),
        }
    }
}
