use super::{
    auto_generated_groups::AutoGeneratedGroupMetadata,
    GroupName,
};
use alloc::borrow::Cow;

#[derive(Debug, PartialEq, Eq, Hash)]
pub(crate) enum GroupKey<'a> {
    AutoGenerated(Cow<'a, AutoGeneratedGroupMetadata>),
    Custom(Cow<'a, GroupName>),
}

impl GroupKey<'_> {
    pub(crate) fn clone(&self) -> GroupKey<'static> {
        match self {
            Self::AutoGenerated(metadata) => {
                GroupKey::AutoGenerated(Cow::Owned(
                    metadata.as_ref().clone(),
                ))
            }
            Self::Custom(name) => GroupKey::Custom(
                Cow::Owned(name.as_ref().clone()),
            ),
        }
    }
}
