use super::GroupName;

#[allow(clippy::partial_pub_fields)]
#[derive(Debug)]
pub(crate) struct AutoGeneratedGroup {
    pub name: GroupName,
    pub(super) cargo_args: Option<&'static [&'static str]>,
}
