pub(crate) use self::{
    test_name::TestName, test_result::TestResult,
};
use super::groups::{auto_generated_groups::AutoGeneratedGroupMetadata, GroupKey};
use crate::{cargo::{
    CargoCommandArgs, CargoRunArgs, CargoTestArgs,
}, state::testing::groups::auto_generated_groups::auto_generated_group_metadata::TargetKind};
use core::cmp::Ordering;
use serde::{Deserialize, Serialize};
pub(crate) use self::test_kind::TestKind;

mod test_kind;
mod test_name;
mod test_result;

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    Hash,
    Serialize,
    Deserialize,
)]
pub(crate) struct Test {
    pub package_name: String,
    pub kind: TestKind,
}

impl Test {
    pub fn from_group_key(
        group_key: &GroupKey<'_>,
        test_name: String,
    ) -> Option<Self> {
        match group_key {
            GroupKey::AutoGenerated(metadata) => {
                let package_name = &metadata.package_name;
                let kind = match &metadata.target_kind {
                    TargetKind::Bin(target_name) => {
                        TestKind::BinTest {
                            target_name: target_name
                                .clone(),
                            test_name,
                        }
                    }
                    TargetKind::Lib(_) => {
                        TestKind::LibTest { test_name }
                    }
                    TargetKind::Test(target_name) => {
                        TestKind::IntegrationTest {
                            target_name: target_name
                                .clone(),
                            test_name,
                        }
                    }
                    TargetKind::Example(target_name) => {
                        TestKind::ExampleTest {
                            target_name: target_name
                                .clone(),
                            test_name,
                        }
                    }
                    TargetKind::Tests(_)
                    | TargetKind::Examples(_) => {
                        return None;
                    }
                };

                Some(Self {
                    package_name: package_name.clone(),
                    kind,
                })
            }
            GroupKey::Custom(_) => None,
        }
    }

    pub fn full_name(&self) -> TestName {
        let package_name = &self.package_name;

        match &self.kind {
            TestKind::Bin { target_name }
            | TestKind::IntegrationTarget { target_name }
            | TestKind::ExampleTarget { target_name } => {
                format!("{package_name}::{target_name}")
                    .into()
            }
            TestKind::BinTest {
                target_name,
                test_name,
            }
            | TestKind::IntegrationTest {
                target_name,
                test_name,
            }
            | TestKind::ExampleTest {
                target_name,
                test_name,
            } => format!(
                "{package_name}::{target_name}::{test_name}"
            )
            .into(),
            TestKind::Lib => package_name.clone().into(),
            TestKind::LibTest { test_name } => {
                format!("{package_name}::{test_name}")
                    .into()
            }
            TestKind::ExampleMain { target_name } => {
                format!(
                    "{package_name}::{target_name}::main"
                )
                .into()
            }
        }
    }

    #[allow(clippy::too_many_lines)]
    pub fn to_cargo_command_args(
        &self,
    ) -> CargoCommandArgs<'_> {
        let package_name = &self.package_name;
        match &self.kind {
            TestKind::Bin { target_name } => {
                CargoTestArgs {
                    args: Some(
                        vec![
                            "--package".into(),
                            package_name.clone().into(),
                            "--bin".into(),
                            target_name.clone().into(),
                        ]
                        .into(),
                    ),
                    ..Default::default()
                }
                .into()
            }
            TestKind::BinTest {
                target_name,
                test_name,
            } => CargoTestArgs {
                args: Some(
                    vec![
                        "--package".into(),
                        package_name.clone().into(),
                        "--bin".into(),
                        target_name.clone().into(),
                        test_name.clone().into(),
                    ]
                    .into(),
                ),
                test_args: Some(&["--exact"]),
                ..Default::default()
            }
            .into(),
            TestKind::Lib => CargoTestArgs {
                args: Some(
                    vec![
                        "--package".into(),
                        package_name.clone().into(),
                        "--lib".into(),
                    ]
                    .into(),
                ),
                ..Default::default()
            }
            .into(),
            TestKind::LibTest { test_name } => {
                CargoTestArgs {
                    args: Some(
                        vec![
                            "--package".into(),
                            package_name.clone().into(),
                            "--lib".into(),
                            test_name.clone().into(),
                        ]
                        .into(),
                    ),
                    test_args: Some(&["--exact"]),
                    ..Default::default()
                }
                .into()
            }
            TestKind::IntegrationTarget { target_name } => {
                CargoTestArgs {
                    args: Some(
                        vec![
                            "--package".into(),
                            package_name.clone().into(),
                            "--test".into(),
                            target_name.clone().into(),
                        ]
                        .into(),
                    ),
                    ..Default::default()
                }
                .into()
            }
            TestKind::IntegrationTest {
                target_name,
                test_name,
            } => CargoTestArgs {
                args: Some(
                    vec![
                        "--package".into(),
                        package_name.clone().into(),
                        "--test".into(),
                        target_name.clone().into(),
                        test_name.clone().into(),
                    ]
                    .into(),
                ),
                test_args: Some(&["--exact"]),
                ..Default::default()
            }
            .into(),
            TestKind::ExampleTarget { target_name } => {
                CargoTestArgs {
                    args: Some(
                        vec![
                            "--package".into(),
                            package_name.clone().into(),
                            "--example".into(),
                            target_name.clone().into(),
                        ]
                        .into(),
                    ),
                    ..Default::default()
                }
                .into()
            }
            TestKind::ExampleMain { target_name } => {
                // TODO: We need to figure out how to know
                // if it existed successfully (status code?)
                CargoRunArgs {
                    args: Some(
                        vec![
                            "--package".into(),
                            package_name.clone().into(),
                            "--example".into(),
                            target_name.clone().into(),
                        ]
                        .into(),
                    ),
                    ..Default::default()
                }
                .into()
            }
            TestKind::ExampleTest {
                target_name,
                test_name,
            } => CargoTestArgs {
                args: Some(
                    vec![
                        "--package".into(),
                        package_name.clone().into(),
                        "--example".into(),
                        target_name.clone().into(),
                        test_name.clone().into(),
                    ]
                    .into(),
                ),
                test_args: Some(&["--exact"]),
                ..Default::default()
            }
            .into(),
        }
    }
}

#[allow(clippy::missing_trait_methods)]
impl Ord for Test {
    fn cmp(&self, other: &Self) -> Ordering {
        self.full_name().cmp(&other.full_name())
    }
}

#[allow(clippy::missing_trait_methods)]
impl PartialOrd for Test {
    fn partial_cmp(
        &self,
        other: &Self,
    ) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}
