use crate::cargo::{
    CargoCommandArgs, CargoRunArgs, CargoTestArgs,
};
use cargo_metadata::Metadata;
use core::{
    cmp::Ordering,
    fmt::{self, Display, Formatter},
    hash::{Hash, Hasher},
    mem::discriminant,
};
use std::collections::{HashMap, HashSet};

#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
pub(crate) struct AutoGeneratedGroupMetadata {
    pub package_name: String,
    pub target_kind: TargetKind,
}

#[derive(Debug, Clone)]
pub(crate) enum TargetKind {
    Bin(String),
    Lib(String),
    Tests(HashSet<String>),
    Test(String),
    Examples(HashSet<String>),
    Example(String),
}

#[allow(clippy::missing_trait_methods)]
impl PartialEq for TargetKind {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::Bin(a), Self::Bin(b))
            | (Self::Lib(a), Self::Lib(b))
            | (Self::Test(a), Self::Test(b))
            | (Self::Example(a), Self::Example(b)) => {
                a.eq(b)
            }
            (Self::Tests(_), Self::Tests(_))
            | (Self::Examples(_), Self::Examples(_)) => {
                true
            }
            _ => false,
        }
    }
}

#[allow(clippy::missing_trait_methods)]
impl Eq for TargetKind {}

#[allow(clippy::missing_trait_methods)]
impl Hash for TargetKind {
    fn hash<H: Hasher>(&self, state: &mut H) {
        discriminant(self).hash(state);
    }
}

#[allow(clippy::match_same_arms)]
#[allow(clippy::missing_trait_methods)]
impl Ord for TargetKind {
    fn cmp(&self, other: &Self) -> Ordering {
        match (self, other) {
            (Self::Bin(a), Self::Bin(b))
            | (Self::Lib(a), Self::Lib(b))
            | (Self::Test(a), Self::Test(b))
            | (Self::Example(a), Self::Example(b)) => {
                a.cmp(b)
            }
            (Self::Tests(_), Self::Tests(_))
            | (Self::Examples(_), Self::Examples(_)) => {
                Ordering::Equal
            }
            (Self::Bin(_), _) => Ordering::Less,
            (Self::Lib(_), other) => {
                if matches!(other, Self::Bin(_)) {
                    Ordering::Greater
                } else {
                    Ordering::Less
                }
            }
            (Self::Tests(_), other) => {
                if matches!(
                    other,
                    Self::Bin(_) | Self::Lib(_)
                ) {
                    Ordering::Greater
                } else {
                    Ordering::Less
                }
            }
            (Self::Test(_), other) => {
                if matches!(
                    other,
                    Self::Bin(_)
                        | Self::Lib(_)
                        | Self::Tests(_)
                ) {
                    Ordering::Greater
                } else {
                    Ordering::Less
                }
            }
            (Self::Examples(_), other) => {
                if matches!(
                    other,
                    Self::Bin(_)
                        | Self::Lib(_)
                        | Self::Tests(_)
                        | Self::Test(_)
                ) {
                    Ordering::Greater
                } else {
                    Ordering::Less
                }
            }
            (Self::Example(_), _) => Ordering::Greater,
        }
    }
}

#[allow(clippy::missing_trait_methods)]
impl PartialOrd for TargetKind {
    fn partial_cmp(
        &self,
        other: &Self,
    ) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl Display for TargetKind {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        match self {
            Self::Bin(target_name) => {
                write!(f, "bin::{target_name}")
            }
            Self::Lib(_target_name) => {
                // There can only be one lib target per
                // package, so we don't need to include the
                // target name.
                write!(f, "lib")
            }
            Self::Test(target_name) => {
                write!(f, "test::{target_name}")
            }
            Self::Tests(_) => write!(f, "tests"),
            Self::Example(target_name) => {
                write!(f, "example::{target_name}")
            }
            Self::Examples(_) => write!(f, "examples"),
        }
    }
}

impl AutoGeneratedGroupMetadata {
    pub fn to_cargo_command_args_for_listing(
        &self,
    ) -> CargoTestArgs<'_> {
        let Self { package_name, target_kind } = self;

        let mut args = match target_kind {
            TargetKind::Bin(target_name) => CargoTestArgs {
                args: Some(
                    vec![
                        "--package".into(),
                        package_name.clone().into(),
                        "--bin".into(),
                        target_name.clone().into(),
                    ]
                    .into(),
                ),
                ..Default::default()
            },
            TargetKind::Lib(_) => CargoTestArgs {
                args: Some(
                    vec![
                        "--package".into(),
                        package_name.clone().into(),
                        "--lib".into(),
                    ]
                    .into(),
                ),
                ..Default::default()
            },
            TargetKind::Test(target_name) => {
                CargoTestArgs {
                    args: Some(
                        vec![
                            "--package".into(),
                            package_name.clone().into(),
                            "--test".into(),
                            target_name.clone().into(),
                        ]
                        .into(),
                    ),
                    ..Default::default()
                }
            }
            TargetKind::Tests(_) => CargoTestArgs {
                args: Some(
                    vec![
                        "--package".into(),
                        package_name.clone().into(),
                        "--test".into(),
                        "*".into(),
                    ]
                    .into(),
                ),
                ..Default::default()
            },
            TargetKind::Example(target_name) => {
                CargoTestArgs {
                    args: Some(
                        vec![
                            "--package".into(),
                            package_name.clone().into(),
                            "--example".into(),
                            target_name.clone().into(),
                        ]
                        .into(),
                    ),
                    ..Default::default()
                }
            }
            TargetKind::Examples(_) => CargoTestArgs {
                args: Some(
                    vec![
                        "--package".into(),
                        package_name.clone().into(),
                        "--examples".into(),
                    ]
                    .into(),
                ),
                ..Default::default()
            },
        };

        args.list = true;
        args
    }

    #[allow(clippy::too_many_lines)]
    pub fn to_cargo_command_args(
        &self,
    ) -> Vec<CargoCommandArgs<'_>> {
        let Self { package_name, target_kind } = self;

        match target_kind {
            TargetKind::Bin(target_name) => {
                vec![
                    CargoTestArgs {
                        args: Some(
                            vec![
                                "--package".into(),
                                package_name.clone().into(),
                                "--bin".into(),
                                target_name.clone().into(),
                            ]
                            .into(),
                        ),
                        ..Default::default()
                    }
                    .into(),
                ]
            }
            TargetKind::Lib(_) => vec![
                CargoTestArgs {
                    args: Some(
                        vec![
                            "--package".into(),
                            package_name.clone().into(),
                            "--lib".into(),
                        ]
                        .into(),
                    ),
                    ..Default::default()
                }
                .into(),
            ],
            TargetKind::Test(target_name) => vec![
                CargoTestArgs {
                    args: Some(
                        vec![
                            "--package".into(),
                            package_name.clone().into(),
                            "--test".into(),
                            target_name.clone().into(),
                        ]
                        .into(),
                    ),
                    ..Default::default()
                }
                .into(),
            ],
            TargetKind::Tests(_) => vec![
                CargoTestArgs {
                    args: Some(
                        vec![
                            "--package".into(),
                            package_name.clone().into(),
                            "--test".into(),
                            "*".into(),
                        ]
                        .into(),
                    ),
                    ..Default::default()
                }
                .into(),
            ],
            TargetKind::Example(target_name) => {
                vec![
                    CargoTestArgs {
                        args: Some(
                            vec![
                                "--package".into(),
                                package_name.clone().into(),
                                "--example".into(),
                                target_name.clone().into(),
                            ]
                            .into(),
                        ),
                        ..Default::default()
                    }
                    .into(),
                    CargoRunArgs {
                        args: Some(
                            vec![
                                "--package".into(),
                                package_name.clone().into(),
                                "--example".into(),
                                target_name.clone().into(),
                            ]
                            .into(),
                        ),
                        ..Default::default()
                    }
                    .into(),
                ]
            }
            TargetKind::Examples(_) => {
                // This only runs the unit tests for the
                // examples, not the main functions.
                vec![
                    CargoTestArgs {
                        args: Some(
                            vec![
                                "--package".into(),
                                package_name.clone().into(),
                                "--examples".into(),
                            ]
                            .into(),
                        ),
                        ..Default::default()
                    }
                    .into(),
                ]
            }
        }
    }
}

#[allow(clippy::too_many_lines)]
pub(in crate::state) fn all_from_metadata(
    metadata: &Metadata,
) -> Vec<AutoGeneratedGroupMetadata> {
    let mut auto_generated_group_metadata = metadata
        .packages
        .iter()
        .flat_map(|package| {
            package.targets.iter().flat_map(|target| {
                target.kind.iter().filter_map(|kind| {
                    // "bin", "example", "test", "bench",
                    // "lib", "custom-build"

                    tracing::trace!(
                        package = %package.name,
                        target = %target.name,
                        kind = %kind,
                        "Checking target kind",
                    );

                    let target_kind = match kind.as_str() {
                        "bin" => TargetKind::Bin,
                        "lib" => TargetKind::Lib,
                        "test" => TargetKind::Test,
                        "example" => TargetKind::Example,
                        _ => return None,
                    };

                    let target_kind =
                        target_kind(target.name.clone());

                    Some(AutoGeneratedGroupMetadata {
                        package_name: package.name.clone(),
                        target_kind,
                    })
                })
            })
        })
        .collect::<Vec<_>>();

    let mut tests_targets = HashMap::new();
    let mut examples_targets = HashMap::new();

    for metadata in &auto_generated_group_metadata {
        #[allow(clippy::wildcard_enum_match_arm)]
        match &metadata.target_kind {
            TargetKind::Test(target_name) => {
                _ = tests_targets
                    .entry(&metadata.package_name)
                    .or_insert_with(HashSet::new)
                    .insert(target_name.clone());
            }
            TargetKind::Example(target_name) => {
                _ = examples_targets
                    .entry(&metadata.package_name)
                    .or_insert_with(HashSet::new)
                    .insert(target_name.clone());
            }
            _ => {}
        }
    }

    let mut additional_groups: Vec<
        AutoGeneratedGroupMetadata,
    > = vec![];

    #[allow(clippy::iter_over_hash_type)]
    for (package_name, tests) in tests_targets {
        if !tests.is_empty() {
            additional_groups.push(
                AutoGeneratedGroupMetadata {
                    package_name: package_name.clone(),
                    target_kind: TargetKind::Tests(tests),
                },
            );
        }
    }

    #[allow(clippy::iter_over_hash_type)]
    for (package_name, examples) in examples_targets {
        if !examples.is_empty() {
            additional_groups.push(
                AutoGeneratedGroupMetadata {
                    package_name: package_name.clone(),
                    target_kind: TargetKind::Examples(
                        examples,
                    ),
                },
            );
        }
    }

    auto_generated_group_metadata
        .append(&mut additional_groups);

    auto_generated_group_metadata
}
